# Generated by Django 3.2.10 on 2022-03-08 15:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0002_alter_post_likes_alter_post_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ('-date', '-update')},
        ),
    ]
