# Generated by Django 3.2.10 on 2022-03-09 12:22

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_profile_followers_profile_following_profile_likes_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(blank=True, default='../static/default/1.png', null=True, upload_to=accounts.models.namer),
        ),
    ]
